<?php

use Nails\Common\Service\View;
use Nails\Factory;

/** @var View $oView */
$oView = Factory::service('View');

$aQuery = array_filter([
    'return_to' => $return_to,
    'remember'  => $remember,
]);

$sQuery   = !empty($aQuery) ? '?' . http_build_query($aQuery) : '';
$sFormUrl = null;

if (isset($user_id) && isset($token)) {
    $sFormUrl = 'auth/mfa/device/' . $user_id . '/' . $token['salt'] . '/' . $token['token'] . $sQuery;
    $sFormUrl = siteUrl($sFormUrl);
}

?>
<div class="nails-auth mfa mfa--device mfa--device--ask center-screen">
    <div class="panel">
        <div class="panel__header">
            <h1 class="panel__title text-center">
                Two Factor Authentication
            </h1>
        </div>
        <div class="panel__body">
            <?php

            echo form_open($sFormUrl, 'class="form"');
            $oView->load('auth/_components/alerts');

            $sFieldKey         = 'mfa_code';
            $sFieldLabel       = 'Please enter a code generated by your device:';
            $sFieldPlaceholder = 'Enter a code generated by your device';
            $sFieldAttr        = 'id="input-' . $sFieldKey . '" autocomplete="off" placeholder="' . $sFieldPlaceholder . '" class="form__control"';

            ?>
            <div class="form__group">
                <label class="form__label" for="input-<?=$sFieldKey?>"><?=$sFieldLabel?></label>
                <?=form_text($sFieldKey, set_value($sFieldKey), $sFieldAttr)?>
                <?=form_error($sFieldKey, '<p class="form__feedback form__feedback--invalid">', '</p>')?>
            </div>
            <div class="form__actions">
                <button type="submit" class="btn btn--block btn--primary">
                    Verify code &amp; Sign in
                </button>
            </div>
            <?=form_close()?>
        </div>
    </div>
</div>
