<?php

use Nails\Common\Service\View;
use Nails\Factory;

/** @var View $oView */
$oView = Factory::service('View');

$aQuery = array_filter([
    'return_to' => $return_to,
    'remember'  => $remember,
]);

$sQuery = !empty($aQuery) ? '?' . http_build_query($aQuery) : '';

?>
<div class="nails-auth mfa mfa--device mfa--device--setup center-screen">
    <div class="panel">
        <div class="panel__header">
            <h1 class="panel__title text-center">
                Set up Two Factor Authentication
            </h1>
        </div>
        <div class="panel__body">
            <?php

            echo form_open('auth/mfa/device/' . $user_id . '/' . $token['salt'] . '/' . $token['token'] . $sQuery, 'class="form"');
            echo form_hidden('mfa_secret', $secret['secret']);

            $oView->load('auth/_components/alerts');

            ?>
            <p>
                This site requires that you use Two Factor Authentication when logging in. To set up, please scan the QR
                code with your device, then enter a valid code.
            </p>
            <p class="text-center">
                <?=img(['src' => $secret['url'], 'class' => 'img-responsive img-thumbnail'])?>
            </p>
            <?php

            $sFieldKey         = 'mfa_code';
            $sFieldLabel       = 'Your code';
            $sFieldPlaceholder = 'Enter a code generated by your device';
            $sFieldAttr        = 'id="input-' . $sFieldKey . '" autocomplete="off" placeholder="' . $sFieldPlaceholder . '" class="form__control"';

            ?>
            <div class="form__group">
                <label class="form__label" for="input-<?=$sFieldKey?>"><?=$sFieldLabel?></label>
                <?=form_text($sFieldKey, set_value($sFieldKey), $sFieldAttr)?>
                <?=form_error($sFieldKey, '<p class="form__feedback form__feedback--invalid">', '</p>')?>
            </div>
            <div class="form__actions">
                <button type="submit" class="btn btn--block btn--primary">
                    Verify code &amp; Sign in
                </button>
            </div>
            <?=form_close()?>
        </div>
    </div>
</div>
